### ISSUE TITLE
Windows version 2.3.1 broke profile switching functionality

### ISSUE THREAD

**Issue by jxlarrea** [ShayBox/Wooting-Profile-Switcher#13]
Since the latest auto update of the app (currently v2.3.1), profile switching no longer works. Additionally, it is impossible to change the profile index using the UI for new or existing rules as the selection control no longer works.

![Screenshot 2023-10-28 032140](https://github.com/ShayBox/Wooting-Profile-Switcher/assets/309902/e70dc450-cafe-4142-bdd7-bcbb79bea8ca)

**Comment by ShayBox** [comment]
You have to update Wootility and your firmware

**Comment by BrutalCSEjziponken** [comment]
@ShayBox didnt wanna create a new thread, but u know if this works on the new v4.6.12-beta? Or any updates needed?

**Comment by ShayBox** [comment]
I haven't tested it, and the Windows build isn't available because of the signing key, but I don't see anything in the changelog that would cause an issue. It might not be able to pull device info from Wootility if that's changed, but as long as you don't reset your WPS config, it should continue using the previous info.
